name=BioLogic_Mini
version=1.0.0
author=Mau Molina Valdez
maintainer=Mauricio Molina Valdez <maubiomedica@gmail.com>
sentence=Libreria nativa para el control directo de salidas BioLogic en ESP32-C3.
paragraph=Permite el control local en tiempo real de las etapas de potencia r1 (GPIO 4) y r2 (GPIO 3), eliminando la dependencia del bus de comunicacion I2C.
category=Device Control
url=https://github.com/maumolinavaldez-pixel/BioLogic_Mini
architectures=esp32
includes=BioLogic.h
dot_a_linkage=true
